import jsPDF from "jspdf";
import autoTable from 'jspdf-autotable';
// @ts-ignore
import htmlDocx from 'html-docx-js/dist/html-docx';
import { saveAs } from 'file-saver';
import { htmlToText } from 'html-to-text';

export type ExportFormat = 'pdf' | 'docx';

export const exportAsset = async (asset: { type: string; name: string; content: any }, format: ExportFormat) => {
    try {
      if (format === 'pdf') {
        const doc = new jsPDF();
        const content = asset.content;
        const title = asset.name || "Learnivo Asset";
        
        doc.setFontSize(20);
        doc.text(title, 20, 20);
        doc.setFontSize(10);
        doc.text(`Generated by Learnivo AI`, 20, 28);
        doc.setLineWidth(0.5);
        doc.line(20, 32, 190, 32);

        let yOffset = 40;

        // Custom PDF logic for different types
        if (asset.type === "Lesson Plan") {
            const plan = typeof content === 'string' ? JSON.parse(content) : content;
            Object.entries(plan).forEach(([day, details]: [string, any]) => {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(14);
                doc.text(day.replace("_", " ").toUpperCase() + ": " + details.sub_topic, 20, yOffset);
                yOffset += 10;

                doc.setFontSize(12);
                doc.text("Learning Objectives:", 20, yOffset);
                yOffset += 7;
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                details.learning_objectives.forEach((obj: string) => {
                    const splitObj = doc.splitTextToSize("• " + obj, 160);
                    doc.text(splitObj, 25, yOffset);
                    yOffset += (splitObj.length * 5);
                });
                yOffset += 5;

                doc.setFont("helvetica", "bold");
                doc.setFontSize(12);
                doc.text("Activities:", 20, yOffset);
                yOffset += 7;
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                details.activities.forEach((act: any) => {
                    doc.text(`• ${act.name} (${act.duration})`, 25, yOffset);
                    yOffset += 6;
                });
                yOffset += 5;

                doc.setFont("helvetica", "bold");
                doc.text("Assessment:", 20, yOffset);
                yOffset += 7;
                doc.setFont("helvetica", "normal");
                const splitAssess = doc.splitTextToSize(details.assessment, 160);
                doc.text(splitAssess, 25, yOffset);
                yOffset += (splitAssess.length * 5) + 10;

                if (yOffset > 250) {
                    doc.addPage();
                    yOffset = 20;
                }
            });
        } else if (asset.type === "Quiz") {
            doc.setFontSize(12);
            content.questions.forEach((q: any, i: number) => {
                doc.setFont("helvetica", "bold");
                const splitText = doc.splitTextToSize(`${i + 1}. ${q.questionText} (${q.marks} Marks)`, 160);
                doc.text(splitText, 20, yOffset);
                yOffset += (splitText.length * 6);
                
                doc.setFont("helvetica", "normal");
                if (q.questionType === "MCQ" && q.options) {
                    q.options.forEach((opt: string, optI: number) => {
                        doc.text(`${String.fromCharCode(97 + optI)}) ${opt}`, 30, yOffset);
                        yOffset += 6;
                    });
                } else if (q.questionType === "FillInTheBlank") {
                    yOffset += 6;
                }
                yOffset += 10;

                if (yOffset > 260) {
                    doc.addPage();
                    yOffset = 20;
                }
            });

            doc.addPage();
            yOffset = 20;
            doc.setFont("helvetica", "bold");
            doc.setFontSize(16);
            doc.text("Answer Key", 20, yOffset);
            yOffset += 15;
            doc.setFontSize(12);
            content.questions.forEach((q: any, i: number) => {
                doc.setFont("helvetica", "bold");
                doc.text(`${i + 1}. Correct Answer: `, 20, yOffset);
                doc.setFont("helvetica", "normal");
                const splitAns = doc.splitTextToSize(q.correctAnswer, 130);
                doc.text(splitAns, 60, yOffset);
                yOffset += (splitAns.length * 6);
                
                doc.setFont("helvetica", "bold");
                doc.text(`Explanation: `, 20, yOffset);
                doc.setFont("helvetica", "normal");
                const splitExp = doc.splitTextToSize(q.explanation, 130);
                doc.text(splitExp, 60, yOffset);
                yOffset += (splitExp.length * 6) + 10;

                if (yOffset > 270) {
                    doc.addPage();
                    yOffset = 20;
                }
            });
        } else if (asset.type === "Rubric") {
           const head = [['Criteria', ...content.criteria[0]?.levels.map((l: any) => l.level)]];
           const body = content.criteria.map((c: any) => [c.criteria, ...c.levels.map((l: any) => l.description)]);
           autoTable(doc, {
               startY: yOffset,
               head: head,
               body: body,
               theme: 'grid',
               styles: { fontSize: 8, cellPadding: 2 },
               headStyles: { fillColor: [79, 70, 229] }
           });
        } else if (asset.type === "Math Solution") {
            doc.setFont("helvetica", "bold");
            doc.text("Solution:", 20, yOffset);
            yOffset += 7;
            doc.setFont("helvetica", "normal");
            const splitSol = doc.splitTextToSize(content.solution, 160);
            doc.text(splitSol, 25, yOffset);
            yOffset += (splitSol.length * 6) + 10;

            doc.setFont("helvetica", "bold");
            doc.text("Explanation:", 20, yOffset);
            yOffset += 7;
            doc.setFont("helvetica", "normal");
            const splitExp = doc.splitTextToSize(content.explanation, 160);
            doc.text(splitExp, 25, yOffset);
        } else {
            // Default generic text or HTML export
            doc.setFontSize(11);
            let text = "";
            if (typeof content === 'string') {
                text = content;
            } else if (content.formattedContent) {
                text = htmlToText(content.formattedContent);
            } else if (content.content) {
                text = typeof content.content === 'string' ? content.content : JSON.stringify(content.content);
            } else {
                text = JSON.stringify(content, null, 2);
            }
            
            const splitText = doc.splitTextToSize(text, 170);
            splitText.forEach((line: string) => {
                if (yOffset > 280) {
                    doc.addPage();
                    yOffset = 20;
                }
                doc.text(line, 20, yOffset);
                yOffset += 6;
            });
        }

        doc.save(`${title.replace(/\s+/g, '_')}.pdf`);
      } else {
        // DOCX Export
        let htmlString = `
          <html>
            <head><meta charset="utf-8"></head>
            <body style="font-family: Arial, sans-serif;">
              <h1 style="color: #4f46e5;">${asset.name}</h1>
              <p style="color: #666;">Generated by Learnivo AI</p>
              <hr/>
        `;

        // Type specific DOCX HTML
         if (asset.type === "Lesson Plan") {
            const plan = typeof asset.content === 'string' ? JSON.parse(asset.content) : asset.content;
            Object.entries(plan).forEach(([day, details]: [string, any]) => {
                htmlString += `
                    <h2 style="margin-top: 20px;">${day.replace("_", " ").toUpperCase()}: ${details.sub_topic}</h2>
                    <h3>Learning Objectives</h3>
                    <ul>${details.learning_objectives.map((o: string) => `<li>${o}</li>`).join('')}</ul>
                    <h3>Activities</h3>
                    <ul>${details.activities.map((a: any) => `<li><strong>${a.name}</strong> (${a.duration})</li>`).join('')}</ul>
                    <h3>Resources</h3>
                    <p>${details.resources.join(', ')}</p>
                    <h3>Assessment</h3>
                    <p>${details.assessment}</p>
                `;
            });
        } else if (asset.type === "Quiz") {
             htmlString += `<h2>Questions</h2>`;
             asset.content.questions.forEach((q: any, i: number) => {
                htmlString += `
                    <p><strong>${i+1}. ${q.questionText} (${q.marks} Marks)</strong></p>
                    ${q.questionType === 'MCQ' ? `<ul>${q.options.map((o: string) => `<li>${o}</li>`).join('')}</ul>` : ''}
                `;
             });
             htmlString += `<br/><br/><h2>Answer Key</h2>`;
             asset.content.questions.forEach((q: any, i: number) => {
                htmlString += `
                    <p><strong>${i+1}. Answer:</strong> ${q.correctAnswer}</p>
                    <p><strong>Explanation:</strong> ${q.explanation}</p>
                `;
             });
        } else if (asset.type === "Rubric") {
            htmlString += `<table border="1" style="border-collapse: collapse; width: 100%;">
                <tr style="background-color: #f3f4f6;">
                    <th>Criteria</th>
                    ${asset.content.criteria[0]?.levels.map((l: any) => `<th>${l.level}</th>`).join('')}
                </tr>
                ${asset.content.criteria.map((c: any) => `
                    <tr>
                        <td><strong>${c.criteria}</strong></td>
                        ${c.levels.map((l: any) => `<td>${l.description}</td>`).join('')}
                    </tr>
                `).join('')}
            </table>`;
        } else if (asset.type === "Math Solution") {
            htmlString += `
                <h2>Solution</h2>
                <p>${asset.content.solution}</p>
                <h2>Explanation</h2>
                <p>${asset.content.explanation}</p>
            `;
        } else {
            let bodyContent = "";
            if (typeof asset.content === 'string') {
                bodyContent = `<p>${asset.content}</p>`;
            } else if (asset.content.formattedContent) {
                bodyContent = asset.content.formattedContent;
            } else if (asset.content.content) {
                bodyContent = typeof asset.content.content === 'string' ? `<p>${asset.content.content}</p>` : `<pre>${JSON.stringify(asset.content.content, null, 2)}</pre>`;
            } else {
                bodyContent = `<pre>${JSON.stringify(asset.content, null, 2)}</pre>`;
            }
            htmlString += bodyContent;
        }

        htmlString += `</body></html>`;
        const converted = htmlDocx.asBlob(htmlString);
        saveAs(converted, `${asset.name.replace(/\s+/g, '_')}.docx`);
      }
      return true;
    } catch (error) {
      console.error("Export error:", error);
      return false;
    }
};
